# Generated by Django 5.0 on 2024-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiftyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'nifty_price',
            },
        ),
    ]
