# Generated by Django 4.0 on 2024-10-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankNiftyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('tick_price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'bank_nifty_price',
            },
        ),
        migrations.CreateModel(
            name='NiftyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('tick_price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'nifty_price',
            },
        ),
    ]
