# Generated by Django 5.1 on 2024-09-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankNiftyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'bank_nifty_price',
            },
        ),
        migrations.AlterField(
            model_name='niftyprice',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
