# Generated by Django 5.1 on 2024-09-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0002_bankniftyprice_alter_niftyprice_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankniftyprice',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
