# Generated by Django 4.0 on 2024-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0003_alter_bankniftyprice_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankniftyprice',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='niftyprice',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
