# Generated by Django 4.0 on 2024-09-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0003_alter_bankniftyprice_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankniftyprice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bankniftyprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bankniftyprice',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='niftyprice',
            name='date',
        ),
        migrations.AlterField(
            model_name='niftyprice',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
