# Generated by Django 4.0 on 2024-09-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0004_alter_bankniftyprice_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankniftyprice',
            old_name='price',
            new_name='tick_price',
        ),
        migrations.RenameField(
            model_name='niftyprice',
            old_name='price',
            new_name='tick_price',
        ),
    ]
