# Generated by Django 4.0 on 2024-10-01 04:32

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backtesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', django_mysql.models.EnumField(choices=[('NIFTY', 'NIFTY'), ('BANKNIFTY', 'BANKNIFTY')])),
                ('strategy', django_mysql.models.EnumField(choices=[('MOMENTUM_V1', 'MOMENTUM_V1')])),
                ('chart_config', models.TextField(max_length=10000)),
                ('trade_config', models.TextField(max_length=10000)),
                ('purpose', models.TextField(max_length=10000, null=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('trade_count', models.IntegerField(null=True)),
                ('winning_trade_count', models.IntegerField(null=True)),
                ('loosing_trade_count', models.IntegerField(null=True)),
                ('success_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'backtesting',
            },
        ),
        migrations.CreateModel(
            name='DailyBacktesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('expected_direction', django_mysql.models.EnumField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')])),
                ('trade_count', models.IntegerField()),
                ('winning_trade_count', models.IntegerField()),
                ('loosing_trade_count', models.IntegerField()),
                ('success_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('backtesting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_backtestings', related_query_name='daily_backtesting', to='backtesting.backtesting')),
            ],
            options={
                'db_table': 'daily_backtesting',
            },
        ),
        migrations.CreateModel(
            name='Optimisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', django_mysql.models.EnumField(choices=[('MOMENTUM_V1', 'MOMENTUM_V1')])),
                ('purpose', models.TextField(max_length=10000, null=True)),
                ('optimised_trade_count', models.IntegerField(null=True)),
                ('optimised_winning_trade_count', models.IntegerField(null=True)),
                ('optimised_loosing_trade_count', models.IntegerField(null=True)),
                ('optimised_success_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('optimised_chart_config', models.TextField(max_length=10000)),
                ('optimised_trade_config', models.TextField(max_length=10000)),
            ],
            options={
                'db_table': 'optimisation',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expected_direction', django_mysql.models.EnumField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')])),
                ('entry_time', models.TimeField()),
                ('entry_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_conditions', models.TextField(max_length=10000)),
                ('exit_time', models.TimeField()),
                ('exit_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_conditions', models.TextField(max_length=10000)),
                ('gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_backtesting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', related_query_name='trade', to='backtesting.dailybacktesting')),
            ],
            options={
                'db_table': 'trade',
            },
        ),
        migrations.AddField(
            model_name='backtesting',
            name='optimisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backtestings', related_query_name='backtesting', to='backtesting.optimisation'),
        ),
    ]
