# Generated by Django 4.0 on 2024-10-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybacktesting',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
