# Generated by Django 4.0 on 2024-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtesting',
            name='state',
        ),
        migrations.AddField(
            model_name='backtesting',
            name='trade_count',
            field=models.IntegerField(null=True),
        ),
    ]
